In [7]:
import numpy as np

In [2]:
arr=[6,7,8,9]

In [3]:
print(type(arr))

<class 'list'>


In [5]:
a=np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(4,)


In [8]:
print(a.dtype)

int32


In [9]:
print(a.ndim)

1


In [11]:
b=np.array([[1,2,3],[4,5,6]])

In [12]:
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
print(b.ndim)

2


In [14]:
b.shape

(2, 3)

In [15]:
print(type(b))

<class 'numpy.ndarray'>


In [16]:
x=np.random.random((2,3))

In [17]:
print(x)

[[0.35082662 0.3581837  0.31629311]
 [0.10375014 0.66574477 0.69673318]]


In [19]:
y=np.zeros((2,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
z=np.identity(5)
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
c=np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d=np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

In [22]:
c+d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [23]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [24]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [25]:
d/c

array([[0.44444444, 0.625     , 0.85714286],
       [9.        , 4.        , 2.33333333]])

In [26]:
c/d

array([[2.25      , 1.6       , 1.16666667],
       [0.11111111, 0.25      , 0.42857143]])

In [30]:
h=np.random.random((4,3))
print(h)

[[0.06374419 0.71037086 0.07838382]
 [0.37719517 0.1972021  0.567529  ]
 [0.86491124 0.83517846 0.90609473]
 [0.10953651 0.033172   0.97773987]]
